CREATE TABLE BUILDREPORTS(
    REPORT_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    SERVERID TEXT[60] NOT NULL,
    BUILD_HASH TEXT[60] NOT NULL,
    PLATFORM_ID TEXT[60] NOT NULL,
    BUILD_STATUS INTEGER,
    ERROR_OUTPUT BLOB,
    BUILD_TIME DATETIME NOT NULL,
    HAS_BINARY INTEGER NOT NULL
);
