CREATE TABLE BUILDREPORTS(
    REPORT_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    SERVERID TEXT[60] NOT NULL,
    BUILD_HASH TEXT[60] NOT NULL,
    PLATFORM_ID TEXT[60] NOT NULL,
    BUILD_STATUS INTEGER,
    ERROR_OUTPUT BLOB,
    BUILD_TIME DATETIME NOT NULL,
    HAS_BINARY INTEGER NOT NULL
);

CREATE TABLE TEST_REPORT(
    TEST_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    RESULT INTEGER NOT NULL,
    BTIME DATETIME NOT NULL
);

CREATE TABLE UNIT_TEST(
    UNIT_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    RESULT INTEGER NOT NULL,
    UNAME TEXT[60] NOT NULL
);

CREATE TABLE TEST_BUILDREL(
    REPORT_ID INTEGER,
    TEST_ID INTEGER,
    FOREIGN KEY(REPORT_ID) REFERENCES BUILDREPORTS(REPORT_ID),
    FOREIGN KEY(TEST_ID) REFERENCES TEST_REPORT(TEST_ID)
);

CREATE TABLE UNIT_TESTREL(
    TEST_ID INTEGER,
    UNIT_ID INTEGER,
    FOREIGN KEY(TEST_ID) REFERENCES TEST_REPORT(TEST_ID),
    FOREIGN KEY(UNIT_ID) REFERENCES UNIT_TEST(UNIT_ID)
);






